version: '2' 
services:
  namenode:
    image: hadoop-namenode:2.0.0-hadoop3.2.0-java8
    container_name: namenode
    restart: always
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870

  datanode:
    image: hadoop-datanode:2.0.0-hadoop3.2.0-java8
    depends_on: 
      - namenode
    restart: always
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    ports:
      - 9864:9864
  spark-master:
    image: spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop.env
  spark-worker:
    image: spark-worker:3.1.1-hadoop3.2
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081
    env_file:
      - ./hadoop.env
  pyspark-notebook:
    image: spark-jupyterlab:3.1.1-hadoop3.2
    container_name: pyspark-notebook
    env_file:
      - ./hadoop.env
    ports:
      - 8888:8888
  hue:
    image: hadoop-filebrowser:2.0.0-hadoop3.2.0-java8
    ports:
      - 8088:8088
    environment:
      - NAMENODE_HOST=namenode
