# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: optional_boolean.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='optional_boolean.proto',
  package='operations_research',
  syntax='proto3',
  serialized_options=b'Z\'operations_research;operations_research',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16optional_boolean.proto\x12\x13operations_research*F\n\x0fOptionalBoolean\x12\x14\n\x10\x42OOL_UNSPECIFIED\x10\x00\x12\x0e\n\nBOOL_FALSE\x10\x02\x12\r\n\tBOOL_TRUE\x10\x03\x42)Z\'operations_research;operations_researchb\x06proto3'
)

_OPTIONALBOOLEAN = _descriptor.EnumDescriptor(
  name='OptionalBoolean',
  full_name='operations_research.OptionalBoolean',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BOOL_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BOOL_FALSE', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BOOL_TRUE', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=47,
  serialized_end=117,
)
_sym_db.RegisterEnumDescriptor(_OPTIONALBOOLEAN)

OptionalBoolean = enum_type_wrapper.EnumTypeWrapper(_OPTIONALBOOLEAN)
BOOL_UNSPECIFIED = 0
BOOL_FALSE = 2
BOOL_TRUE = 3


DESCRIPTOR.enum_types_by_name['OptionalBoolean'] = _OPTIONALBOOLEAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
