# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import linear_solver_pb2 as linear__solver__pb2


class MIPServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MIPModel = channel.unary_unary(
                '/operations_research.MIPService/MIPModel',
                request_serializer=linear__solver__pb2.MPModelRequest.SerializeToString,
                response_deserializer=linear__solver__pb2.MPSolutionResponse.FromString,
                )


class MIPServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MIPModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MIPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MIPModel': grpc.unary_unary_rpc_method_handler(
                    servicer.MIPModel,
                    request_deserializer=linear__solver__pb2.MPModelRequest.FromString,
                    response_serializer=linear__solver__pb2.MPSolutionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'operations_research.MIPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MIPService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MIPModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/operations_research.MIPService/MIPModel',
            linear__solver__pb2.MPModelRequest.SerializeToString,
            linear__solver__pb2.MPSolutionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
